'use strict';
const canvas=document.getElementById('spaceMap'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);
const TYPES={earth:{name:'地球型',color:'#55c989'},mars:{name:'火星型',color:'#df7658'},gas:{name:'ガス惑星',color:'#68aee8'}};
const NAMES=['アケルナル','ベルダン','トリトン','ルメリア','ガウス','ハルモニア','ネレイド','オルフェ','カノープス','エリダヌス','サガン','テーベ','ミネルヴァ','イオニア','ケプラー','アルカディア','リゲル','セレス','ソラリス','タルシス'];
const FACTIONS=[{id:'player',name:'総督府',color:'#5dd7ff'},{id:'zora',name:'ゾラ共同体',color:'#ff6b74'},{id:'mira',name:'ミラ交易連盟',color:'#ffcc66'},{id:'nox',name:'ノクス評議会',color:'#b08cff'}];
let state,selectedId=null,timer=null,speed=1;
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}function pick(a){return a[rand(0,a.length-1)]}
function makePlanet(i){const type=pick(['earth','mars','gas']);let ore,deut,cap;
 if(type==='earth'){ore=rand(35,70);deut=rand(35,70);cap=rand(500,1000)}
 if(type==='mars'){ore=rand(70,100);deut=rand(10,35);cap=rand(200,500)}
 if(type==='gas'){ore=0;deut=rand(80,120);cap=rand(50,200)}
 return{id:i,name:NAMES[i],x:rand(7,93),y:rand(8,92),type,ore,deut,cap,pop:0,owner:null,explored:0,defense:rand(5,30),facilities:{ore:0,fuel:0,dock:0,sensor:0},stock:{materials:0,fuel:0}}}
function newGame(){const planets=[];for(let i=0;i<20;i++){let p,ok;do{p=makePlanet(i);ok=planets.every(q=>Math.hypot(p.x-q.x,p.y-q.y)>8)}while(!ok);planets.push(p)}
 const home=planets[0];Object.assign(home,{name:'プロキオン首都星',type:'earth',ore:50,deut:50,cap:600,pop:300,owner:'player',explored:3,defense:30,facilities:{ore:1,fuel:1,dock:1,sensor:1},stock:{materials:500,fuel:500}});
 const others=[...planets.slice(1)].sort(()=>Math.random()-.5);['zora','mira','nox'].forEach((f,idx)=>{for(let k=0;k<3;k++){const p=others[idx*3+k];p.owner=f;p.pop=rand(100,Math.min(p.cap,450));p.explored=0;p.facilities={ore:1,fuel:1,dock:k===0?1:0,sensor:0};}});
 state={year:1,turn:0,money:3000,planets,fleets:[{id:1,name:'第1探査隊',type:'scout',level:1,at:0,target:null,progress:0,eta:0,fuel:100,status:'待機'}],nextFleet:2,relations:{zora:0,mira:0,nox:0},contacted:{},gameOver:false};selectedId=0;log('星域統治を開始しました。','good');setSpeed(1);renderAll()}
function total(k){return Math.floor(state.planets.filter(p=>p.owner==='player').reduce((s,p)=>s+p.stock[k],0))}
function tick(){if(state.gameOver)return;state.turn++;moveFleets();produce();if(state.turn>=100){state.turn=0;state.year++;annual()}npcTurn();renderAll()}
function annual(){let tax=0;state.planets.forEach(p=>{if(p.owner==='player'){const factor=p.type==='earth'?1.2:p.type==='mars'?.8:.5;p.pop=Math.min(p.cap,p.pop+p.pop*.02*factor*(1-p.pop/p.cap));tax+=Math.floor(p.pop/10)*100}});state.money+=tax;log(`${state.year}年になりました。税収${tax}を得ました。`,'good');if(state.year>150)endGame('150年が経過しました。星域統一には至りませんでした。')}
function produce(){state.planets.forEach(p=>{if(p.owner==='player'){p.stock.materials=Math.min(1000,p.stock.materials+p.ore*p.facilities.ore*2/100);p.stock.fuel=Math.min(1000,p.stock.fuel+p.deut*p.facilities.fuel*2/100)}})}
function moveFleets(){state.fleets.forEach(f=>{if(f.target===null)return;f.progress++;if(f.progress>=f.eta){f.at=f.target;f.target=null;f.progress=0;f.status='待機';arrive(f)}})}
function arrive(f){const p=state.planets[f.at];p.explored=Math.max(p.explored,f.type==='scout'?3:2);log(`${f.name}が${p.name}に到達しました。`,'good');selectedId=p.id;if(!p.owner){p.owner='player';p.pop=10;p.defense=5;log(`${p.name}を無所属惑星として編入しました。`,'good')}else if(p.owner!=='player'&&!state.contacted[p.owner]){state.contacted[p.owner]=true;showContact(p.owner,p)}checkVictory()}
function npcTurn(){if(state.turn%10)return;['zora','mira','nox'].forEach(fid=>{if(Math.random()<.035&&state.relations[fid]<-25){const targets=state.planets.filter(p=>p.owner==='player');if(targets.length){const p=pick(targets);p.defense=Math.max(0,p.defense-rand(2,8));log(`${FACTIONS.find(f=>f.id===fid).name}が${p.name}周辺で軍事行動。`,'bad')}}})}
function showContact(fid,p){const fac=FACTIONS.find(f=>f.id===fid);showModal(`${fac.name}と接触`,`探査船は${p.name}で異種族の通信を受信しました。接触方針を選択してください。`,[
 ['友好的に呼びかける',()=>{const success=Math.random()<.7;state.relations[fid]+=success?25:5;log(`${fac.name}との初回外交は${success?'成功':'慎重な反応'}でした。`,success?'good':'warn')}],
 ['中立的に観察する',()=>{state.relations[fid]+=5;log(`${fac.name}を中立的に観察しました。`,'warn')}],
 ['威圧する',()=>{state.relations[fid]-=30;log(`${fac.name}を威圧し、関係が悪化しました。`,'bad')}]
 ])}
function sendScout(p){const f=state.fleets.find(x=>x.type==='scout'&&x.target===null);if(!f)return log('待機中の探査船がありません。','warn');const from=state.planets[f.at],dist=Math.hypot(from.x-p.x,from.y-p.y),cost=Math.ceil(dist);if(f.fuel<cost)return log('探査船の燃料が不足しています。','warn');f.fuel-=cost;f.target=p.id;f.eta=Math.max(2,Math.ceil(dist/2));f.progress=0;f.status='航行中';log(`${f.name}を${p.name}へ派遣しました。到着まで${f.eta}ターン。`,'good')}
function colonize(p){if(p.owner)return;if(state.money<300||total('materials')<100||total('fuel')<50)return log('植民に必要な資源が足りません。','warn');spendStock('materials',100);spendStock('fuel',50);state.money-=300;p.owner='player';p.pop=10;p.explored=3;log(`${p.name}への植民を開始しました。`,'good')}
function build(type){const home=state.planets.find(p=>p.owner==='player'&&p.facilities.dock>0);const data={scout:['探査船',600,150],battleship:['戦艦',1500,450],transport:['輸送船',800,250]}[type];if(!home||state.money<data[1]||total('materials')<data[2])return log('建造資源または造船ドックが不足しています。','warn');state.money-=data[1];spendStock('materials',data[2]);state.fleets.push({id:state.nextFleet++,name:`${data[0]}隊${state.nextFleet-1}`,type,level:1,at:home.id,target:null,progress:0,eta:0,fuel:type==='battleship'?80:100,status:'待機'});log(`${data[0]}を建造しました。`,'good')}
function spendStock(k,n){for(const p of state.planets.filter(p=>p.owner==='player')){const take=Math.min(p.stock[k],n);p.stock[k]-=take;n-=take;if(n<=0)break}}
function attack(p){const battles=state.fleets.filter(f=>f.type==='battleship'&&f.target===null);if(!battles.length)return log('待機中の戦艦がありません。','warn');const power=battles.length*50;const result=power>=p.defense;if(result){const old=p.owner;p.owner='player';p.pop*=.9;p.defense=10;p.explored=3;state.relations[old]=-100;log(`${p.name}を占領しました。`,'good')}else{state.fleets=state.fleets.filter(f=>f.type!=='battleship'||Math.random()>.5);log(`${p.name}攻略に失敗しました。`,'bad')}checkVictory()}
function ally(fid){if(state.relations[fid]>=60){state.relations[fid]=100;log(`${FACTIONS.find(f=>f.id===fid).name}と同盟を締結しました。`,'good');checkVictory()}else log('同盟には関係値60以上が必要です。','warn')}
function gift(fid){if(state.money<500)return log('資金が不足しています。','warn');state.money-=500;state.relations[fid]=Math.min(100,state.relations[fid]+15);log(`${FACTIONS.find(f=>f.id===fid).name}へ支援を行いました。`,'good')}
function checkVictory(){const remaining=['zora','mira','nox'].filter(fid=>state.planets.some(p=>p.owner===fid)&&state.relations[fid]<60);if(!remaining.length)endGame('星域から敵対する独立勢力がなくなりました。星域統一です。')}
function endGame(text){state.gameOver=true;setSpeed(0);showModal('ゲーム終了',text,[['新しい星域',newGame]])}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=devicePixelRatio||1;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';for(let i=0;i<110;i++){const x=(i*137%1000)/1000*w,y=(i*83%700)/700*h;ctx.globalAlpha=.18+(i%5)/10;ctx.fillRect(x,y,1,1)}ctx.globalAlpha=1;
 state.planets.forEach(p=>{const x=p.x/100*w,y=p.y/100*h,r=p.id===selectedId?12:8;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=p.explored?TYPES[p.type].color:'#718092';ctx.fill();if(p.owner){ctx.strokeStyle=FACTIONS.find(f=>f.id===p.owner).color;ctx.lineWidth=3;ctx.stroke()}if(p.id===selectedId){ctx.beginPath();ctx.arc(x,y,17,0,Math.PI*2);ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.stroke()}ctx.fillStyle='#b8ccda';ctx.font='11px system-ui';ctx.fillText(p.explored?p.name:`未踏-${p.id}`,x+12,y+4)});
 state.fleets.forEach(f=>{const a=state.planets[f.at],b=f.target===null?a:state.planets[f.target],t=f.target===null?0:f.progress/f.eta,x=(a.x+(b.x-a.x)*t)/100*w,y=(a.y+(b.y-a.y)*t)/100*h;ctx.fillStyle=f.type==='battleship'?'#ff786f':f.type==='transport'?'#ffcc66':'#5dd7ff';ctx.beginPath();ctx.moveTo(x,y-6);ctx.lineTo(x+5,y+5);ctx.lineTo(x-5,y+5);ctx.closePath();ctx.fill()})}
function renderAll(){if(!state)return;$('year').textContent=state.year;$('turn').textContent=state.turn;$('money').textContent=Math.floor(state.money);$('population').textContent=Math.floor(state.planets.filter(p=>p.owner==='player').reduce((s,p)=>s+p.pop,0));$('materials').textContent=total('materials');$('fuel').textContent=total('fuel');renderFleet();renderDiplomacy();renderDetail();draw()}
function renderFleet(){$('fleetList').innerHTML=state.fleets.map(f=>`<div class="card"><strong>${f.name}</strong>${f.status}｜燃料 ${Math.floor(f.fuel)}${f.target!==null?`<br>到着まで ${f.eta-f.progress}ターン`:''}</div>`).join('')||'<div class="card">艦船なし</div>'}
function renderDiplomacy(){$('diplomacyList').innerHTML=['zora','mira','nox'].map(fid=>{const f=FACTIONS.find(x=>x.id===fid),known=state.contacted[fid];return `<div class="card"><strong style="color:${f.color}">${known?f.name:'未接触勢力'}</strong>関係 ${known?state.relations[fid]:'不明'}${known?`<br><button onclick="gift('${fid}')">支援</button><button onclick="ally('${fid}')">同盟</button>`:''}</div>`}).join('')}
function renderDetail(){const p=state.planets.find(x=>x.id===selectedId);if(!p){$('detail').textContent='惑星を選択してください。';return}const owner=p.owner?FACTIONS.find(f=>f.id===p.owner).name:'無所属';$('detail').innerHTML=p.explored?`<h3>${p.name}</h3><div class="row"><span>種類</span><b>${TYPES[p.type].name}</b></div><div class="row"><span>所属</span><b>${owner}</b></div><div class="row"><span>人口</span><b>${Math.floor(p.pop)}万 / ${p.cap}万</b></div><div class="row"><span>鉱石指数</span><b>${p.ore}</b></div><div class="row"><span>重水素指数</span><b>${p.deut}</b></div><div class="row"><span>防衛力</span><b>${p.defense}</b></div><div class="row"><span>資材備蓄</span><b>${Math.floor(p.stock.materials)}</b></div><div class="row"><span>燃料備蓄</span><b>${Math.floor(p.stock.fuel)}</b></div>`:`<h3>未踏惑星 ${p.id}</h3><p>詳細不明。探査船を派遣してください。</p>`;
 let buttons=[];if(!p.explored)buttons.push(`<button onclick="sendScout(state.planets[${p.id}])">探査</button>`);else if(!p.owner)buttons.push(`<button onclick="colonize(state.planets[${p.id}])">植民</button>`);else if(p.owner!=='player')buttons.push(`<button onclick="attack(state.planets[${p.id}])">攻略</button>`);$('actions').innerHTML=buttons.join('')}
function log(msg,cls=''){const d=document.createElement('div');d.className=cls;d.textContent=`${state?state.year:1}年 ${state?state.turn:0}: ${msg}`;$('log').prepend(d);while($('log').children.length>30)$('log').lastChild.remove()}
function showModal(title,text,actions){$('modalTitle').textContent=title;$('modalText').textContent=text;$('modalActions').innerHTML='';actions.forEach(([label,fn])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{$('modal').classList.add('hidden');fn();renderAll()};$('modalActions').appendChild(b)});$('modal').classList.remove('hidden');setSpeed(0)}
function setSpeed(v){speed=v;document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',+b.dataset.speed===v));clearInterval(timer);if(v>0)timer=setInterval(tick,3000/v)}
document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>setSpeed(+b.dataset.speed));
$('newGame').onclick=newGame;$('buildScout').onclick=()=>build('scout');$('buildBattleship').onclick=()=>build('battleship');$('buildTransport').onclick=()=>build('transport');
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;let best=null,d=5;state.planets.forEach(p=>{const n=Math.hypot(p.x-x,p.y-y);if(n<d){d=n;best=p}});if(best){selectedId=best.id;renderAll()}});window.addEventListener('resize',draw);newGame();
