'use strict';
const $=id=>document.getElementById(id),map=$('map'),ctx=map.getContext('2d');
const TYPES={earth:['地球型','#58c98b'],mars:['火星型','#df7658'],gas:['ガス惑星','#68aee8']},FACS={player:['総督府','#5dd7ff'],zora:['ゾラ共同体','#ff7078'],mira:['ミラ交易連盟','#ffd16e'],nox:['ノクス評議会','#ae8cff']};
const NAMES=['プロキオン','アケルナル','ベルダン','トリトン','ルメリア','ガウス','ハルモニア','ネレイド','オルフェ','カノープス','エリダヌス','サガン','テーベ','ミネルヴァ','イオニア','ケプラー','アルカディア','リゲル','セレス','ソラリス'];
const SHIPS={scout:{name:'探査船',hp:45,atk:8,def:5,speed:2,maxFuel:38,cost:[600,150],turns:18},battleship:{name:'戦艦',hp:130,atk:50,def:25,speed:1.2,maxFuel:26,cost:[1500,450],turns:45},transport:{name:'輸送船',hp:75,atk:3,def:8,speed:1,maxFuel:32,cost:[800,250],turns:28}};
const FAC={orePlant:['鉱石プラント','ground',500,120,20],fuelPlant:['燃料プラント','ground',500,120,20],habitat:['居住区','ground',650,150,25],defense:['防衛基地','ground',800,200,30],dock:['造船ドック','orbital',1000,250,35],sensor:['探査基地','orbital',700,160,24],battery:['軌道砲台','orbital',1100,280,38],storage:['貯蔵ステーション','orbital',750,180,26]};
const RANKS=[['候補生','◇',0],['少尉','◆',20],['中尉','◆◆',55],['大尉','◆◆◆',100],['少佐','★',170],['中佐','★★',260],['大佐','★★★',380]];
let S,sel,route,timer,history=[];const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,pick=a=>a[rand(0,a.length-1)];
function makePlanet(i){const type=pick(['earth','mars','gas']);return{id:i,name:NAMES[i],x:rand(5,195),y:rand(6,194),type,ore:type==='gas'?0:rand(type==='mars'?70:35,type==='mars'?100:70),deut:rand(type==='gas'?80:type==='mars'?10:35,type==='gas'?120:type==='mars'?35:70),cap:rand(type==='earth'?500:type==='mars'?200:50,type==='earth'?1000:type==='mars'?500:200),pop:0,owner:null,explored:false,usable:Math.random()>=.22,materials:0,fuel:0,defense:rand(10,45),dock:0,dockPool:[],buildQueue:[],facilities:{orePlant:0,fuelPlant:0,habitat:0,defense:0,dock:0,sensor:0,battery:0,storage:0},facilityQueue:null,independent:false}}
function makeFleet(id,owner,at,types,name){return{id,owner,at,target:null,progress:0,eta:0,burn:0,order:'待機',name,commander:null,ships:types.map((t,i)=>({id:`${id}-${i}`,type:t,hp:SHIPS[t].hp,fuel:SHIPS[t].maxFuel,level:1,upgrade:{weapon:0,armor:0,tank:0}}))}}
function newGame(){let ps=[];for(let i=0;i<20;i++){let p;do{p=makePlanet(i)}while(ps.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<8));ps.push(p)}Object.assign(ps[0],{x:100,y:100,name:'プロキオン首都星',type:'earth',ore:50,deut:50,cap:600,pop:300,owner:'player',explored:true,usable:true,materials:500,fuel:500,dock:1,facilities:{orePlant:1,fuelPlant:1,habitat:0,defense:0,dock:1,sensor:1,battery:1,storage:0}});[20,27,34].forEach((d,i)=>{const p=ps[i+1],a=[25,145,265][i]*Math.PI/180;Object.assign(p,{x:100+Math.cos(a)*d,y:100+Math.sin(a)*d,owner:null,usable:true,explored:false})});const rest=ps.slice(4).sort(()=>Math.random()-.5);['zora','mira','nox'].forEach((o,j)=>rest.slice(j*3,j*3+3).forEach(p=>{p.owner=o;p.pop=rand(100,300)}));const xp=[180,110,65,25,0,0,0,0],names=['アレン・カイ','ミナ・ロウ','トウマ・レン','セラ・ノイン','ユナ・ベル','ガイル・オルド','リオ・サーン','エマ・ヴァル'],people=names.map((name,id)=>{const r=rankByXp(xp[id]),tier=RANKS.indexOf(r);return{id,name,xp:xp[id],pilot:rand(18+tier*10,38+tier*12),force:rand(18+tier*10,38+tier*12),diplomacy:rand(18+tier*10,38+tier*12),assignment:null,alive:true}});const f=makeFleet(1,'player',0,['scout'],'第1探査艦隊'),best=[...people].sort((a,b)=>b.pilot-a.pilot)[0];f.commander=best.id;best.assignment=f.id;S={year:1,turn:0,money:3000,planets:ps,fleets:[f],people,relations:{zora:0,mira:0,nox:0},contacted:{},nextFleet:2,npcKnown:{zora:[],mira:[],nox:[]}};['zora','mira','nox'].forEach((fac,j)=>{const home=rest[j*3];S.npcKnown[fac]=[home.id];S.fleets.push(makeFleet(100+j,fac,home.id,['scout','battleship','transport'],`${FACS[fac][0]}第1艦隊`))});sel={kind:'planet',id:0};route=null;history=[];log('星域統治を開始しました。','good');speed(1);render()}
function rankByXp(x){let r=RANKS[0];for(const a of RANKS)if(x>=a[2])r=a;return r}function commander(f){return S.people.find(p=>p.id===f.commander&&p.alive!==false)}function currentPos(f){const a=S.planets[f.at];if(f.target===null)return{x:a.x,y:a.y};const b=S.planets[f.target],t=f.progress/f.eta;return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function range(f){return Math.floor(Math.min(...f.ships.map(s=>s.fuel))/Math.max(.5,1-(commander(f)?.pilot||0)*.004))}function routeInfo(f,pid){const d=distance(currentPos(f),S.planets[pid]),sp=Math.min(...f.ships.map(s=>SHIPS[s.type].speed));return{d,turns:Math.max(2,Math.ceil(d/sp)),ok:d<=range(f)}}
function tick(){S.turn++;processFacilities();processShips();if(S.turn%15===0)npcOrders();S.planets.filter(p=>p.owner==='player').forEach(p=>{p.materials=Math.min(1000,p.materials+p.ore*.02*(1+p.facilities.orePlant*.25));p.fuel=Math.min(1000,p.fuel+p.deut*.02*(1+p.facilities.fuelPlant*.25))});S.fleets.forEach(f=>{if(f.target===null)return;if(f.ships.some(s=>s.fuel<f.burn)){f.target=null;f.order='燃料切れ・漂流';return log(`${f.name}が漂流しました。`,'bad')}f.ships.forEach(s=>s.fuel-=f.burn);if(++f.progress>=f.eta){f.at=f.target;f.target=null;f.progress=0;f.burn=0;f.order='待機';arrive(f)}});if(S.turn>=100){S.turn=0;S.year++;annualRecruit();S.money+=S.planets.filter(p=>p.owner==='player').reduce((n,p)=>n+Math.floor(p.pop/10)*100,0)}if(S.turn%10===0)save(false);render()}
function npcOrders(){
 for(const f of S.fleets.filter(x=>x.owner!=='player'&&!String(x.owner).startsWith('independent-')&&x.target===null&&x.ships.length)){
  const here=S.planets[f.at],candidates=S.planets.filter(p=>p.id!==here.id&&distance(here,p)<=Math.max(36,range(f)));
  if(!candidates.length)continue;
  const unexplored=candidates.filter(p=>!(S.npcKnown[f.owner]||[]).includes(p.id));
  const targets=unexplored.length?unexplored:candidates.filter(p=>!p.owner||p.owner===f.owner);
  const target=pick(targets.length?targets:candidates),r=routeInfo(f,target.id);if(!r.ok)continue;
  f.target=target.id;f.progress=0;f.eta=r.turns;f.burn=Math.ceil(r.d*.8)/r.turns;f.order=unexplored.includes(target)?'探査航行':'哨戒航行';
 }
}
let fleetBattle=null;
function startFleetBattle(player,enemy,planet){
 speed(0);fleetBattle={player,enemy,planet,round:0,logs:[],playerMax:player.ships.reduce((n,x)=>n+SHIPS[x.type].hp,0),enemyMax:enemy.ships.reduce((n,x)=>n+SHIPS[x.type].hp,0)};renderFleetBattle();
}
function battleHp(f){return f.ships.reduce((n,x)=>n+Math.max(0,x.hp),0)}
function renderFleetBattle(){const b=fleetBattle,p=b.player,e=b.enemy,pp=Math.max(0,battleHp(p)/b.playerMax*100),ep=Math.max(0,battleHp(e)/b.enemyMax*100);$('modal').classList.remove('hidden');$('modalTitle').textContent=`艦隊戦 第${b.round+1}ラウンド`;$('modalBody').innerHTML=`<div class="fleetBattleGrid"><div class="fleetBattlePanel"><b>${p.name}</b>${gauge(pp)}残存 ${p.ships.length}隻</div><div class="fleetBattlePanel enemy"><b>${e.name}</b>${gauge(ep)}残存 ${e.ships.length}隻</div></div><div class="fleetBattleLog">${b.logs.slice(-10).map(x=>`<div>${x}</div>`).join('')||'敵艦隊を確認しました。'}</div><div class="defenseControls"><button id="fleetNext">次のラウンド</button><button id="fleetAuto">自動進行</button><button id="fleetRetreat">撤退</button></div>`;$('modalButtons').innerHTML='';$('fleetNext').onclick=fleetBattleRound;$('fleetAuto').onclick=()=>{let n=20;while(fleetBattle&&n--)fleetBattleRound()};$('fleetRetreat').onclick=()=>finishFleetBattle(false,true)}
function fleetBattleRound(){const b=fleetBattle;if(!b)return;b.round++;fleetVolley(b.player,b.enemy,'自軍');if(b.enemy.ships.length)fleetVolley(b.enemy,b.player,'敵軍');if(!b.player.ships.length||!b.enemy.ships.length||b.round>=10)return finishFleetBattle(b.player.ships.length&&(!b.enemy.ships.length||battleHp(b.player)>=battleHp(b.enemy)),false);renderFleetBattle()}
function fleetVolley(a,d,label){for(const ship of [...a.ships]){if(!d.ships.length)break;const target=pick(d.ships),sd=SHIPS[ship.type],td=SHIPS[target.type],damage=Math.max(1,Math.round(sd.atk*(.7+Math.random()*.6)-td.def*.45));target.hp-=damage;fleetBattle.logs.push(`${label} ${sd.name}が${td.name}へ${damage}ダメージ。`);if(target.hp<=0){d.ships=d.ships.filter(x=>x!==target);fleetBattle.logs.push(`${td.name}を撃沈。`)}}}
function finishFleetBattle(win,retreat){const b=fleetBattle,p=b.player,e=b.enemy,planet=b.planet;fleetBattle=null;S.fleets=S.fleets.filter(f=>f.ships.length);if(retreat)return result('撤退',`敵艦隊との戦闘を離脱しました。<br>自軍残存 ${p.ships.length}隻`,()=>render());if(win)return result('艦隊戦勝利',`${e.name}を撃破しました。<br>自軍残存 ${p.ships.length}隻`,()=>{if(planet.owner&&planet.owner!=='player')arrivalDialog(p,planet);else render()});result('艦隊戦敗北',`${p.name}は敗北しました。<br>自軍残存 ${p.ships.length}隻`,()=>render())}
function canOccupy(f,p){return !!(f&&p&&p.explored&&p.usable&&p.owner&&p.owner!=='player'&&f.at===p.id&&f.target===null&&f.ships.some(s=>s.type==='battleship')&&f.ships.some(s=>s.type==='transport'))}
function occupationPower(f){return f.ships.filter(s=>s.type==='battleship').length*55+f.ships.filter(s=>s.type==='transport').length*40+(commander(f)?.force||0)}
function occupationResistance(p){return Math.max(30,p.defense+Math.floor(p.pop/12))}
let defenseBattle=null;
function occupyPlanet(fid,pid){
 const f=S.fleets.find(x=>x.id===fid),p=S.planets[pid];
 if(!canOccupy(f,p))return result('占領不可','占領には、対象星系に到着済みの戦艦と輸送船を含む艦隊が必要です。',()=>render());
 speed(0);
 defenseBattle={fleet:f,planet:p,round:0,stage:'orbital',orbitalHp:Math.max(40,(p.facilities?.battery||0)*90+p.defense*.5),groundHp:Math.max(30,p.defense+Math.floor(p.pop/15)),fleetMax:f.ships.reduce((n,x)=>n+SHIPS[x.type].hp,0),logs:[]};
 renderDefenseBattle();
}
function fleetCurrentHp(f){return f.ships.reduce((n,x)=>n+Math.max(0,x.hp),0)}
function renderDefenseBattle(){
 const b=defenseBattle;if(!b)return;const f=b.fleet,p=b.planet,fp=Math.max(0,fleetCurrentHp(f)/b.fleetMax*100),targetMax=b.stage==='orbital'?Math.max(40,(p.facilities?.battery||0)*90+p.defense*.5):Math.max(30,p.defense+Math.floor(p.pop/15)),tp=Math.max(0,(b.stage==='orbital'?b.orbitalHp:b.groundHp)/targetMax*100);
 $('modal').classList.remove('hidden');$('modalTitle').textContent=`${p.name} 防衛戦 第${b.round+1}ラウンド`;
 $('modalBody').innerHTML=`<div class="defenseStage"><b>段階：</b>${b.stage==='orbital'?'軌道防衛網との戦闘':'惑星防衛軍との戦闘'}</div><div class="defenseGrid"><div class="defensePanel"><b>${f.name}</b><div class="fuel defenseBar"><i style="width:${fp}%;background:var(--green)"></i></div>残存艦：${f.ships.length}隻<br>攻撃力：${occupationPower(f)}</div><div class="defensePanel"><b>${p.name}</b><div class="fuel defenseBar"><i style="width:${tp}%"></i></div>${b.stage==='orbital'?`軌道防衛耐久：${Math.max(0,Math.ceil(b.orbitalHp))}`:`地上防衛力：${Math.max(0,Math.ceil(b.groundHp))}`}<br>人口：${Math.floor(p.pop)}万</div></div><div class="defenseLog">${b.logs.slice(-10).map(x=>`<div>${x}</div>`).join('')||'攻撃開始を待っています。'}</div><div class="defenseControls"><button id="defenseNext">次のラウンド</button><button id="defenseAuto">自動進行</button><button id="defenseAbort">攻略中止</button></div>`;
 $('modalButtons').innerHTML='';$('defenseNext').onclick=defenseRound;$('defenseAuto').onclick=autoDefense;$('defenseAbort').onclick=()=>{defenseBattle=null;closeModal();log('占領作戦を中止しました。','warn');render()};
}
function defenseRound(){
 const b=defenseBattle;if(!b)return;const f=b.fleet,p=b.planet;b.round++;
 const battleships=f.ships.filter(s=>s.type==='battleship');if(!battleships.length||!f.ships.some(s=>s.type==='transport'))return finishDefense(false,'攻略に必要な戦艦または輸送船を失いました。');
 const attack=Math.max(5,Math.round(battleships.length*SHIPS.battleship.atk*(.35+Math.random()*.25)+(commander(f)?.force||0)*.25));
 if(b.stage==='orbital'){
  b.orbitalHp-=attack;b.logs.push(`攻略艦隊が軌道防衛網へ${attack}ダメージ。`);
  if(b.orbitalHp<=0){b.logs.push('軌道防衛網を突破。惑星防衛軍との戦闘へ移行。');b.stage='ground';return renderDefenseBattle()}
  planetaryCounterattack(f,Math.max(4,Math.round((p.facilities?.battery||1)*14+p.defense*.08)),'軌道砲台');
 }else{
  b.groundHp-=attack;b.logs.push(`攻略艦隊が惑星防衛軍へ${attack}ダメージ。`);
  if(b.groundHp<=0)return resolveLanding();
  planetaryCounterattack(f,Math.max(3,Math.round(p.defense*.12+p.pop/80)),'惑星防衛軍');
 }
 if(!f.ships.length)return finishDefense(false,'攻略艦隊が全滅しました。');renderDefenseBattle();
}
function planetaryCounterattack(f,base,label){const target=pick(f.ships),damage=Math.max(1,Math.round(base*(.7+Math.random()*.6)));target.hp-=damage;defenseBattle.logs.push(`${label}の反撃。${SHIPS[target.type].name}へ${damage}ダメージ。`);if(target.hp<=0){f.ships=f.ships.filter(x=>x!==target);defenseBattle.logs.push(`${SHIPS[target.type].name}が撃沈されました。`)}}
function autoDefense(){let guard=30;while(defenseBattle&&guard--)defenseRound()}
function resolveLanding(){const b=defenseBattle,f=b.fleet,p=b.planet,attack=occupationPower(f),resist=occupationResistance(p);b.logs.push(`降下部隊を投入。占領力${attack}、最終抵抗力${resist}。`);finishDefense(attack>=resist,attack>=resist?'惑星防衛軍が降伏しました。':'降下部隊が撃退されました。')}
function finishDefense(success,message){const b=defenseBattle;if(!b)return;const f=b.fleet,p=b.planet;defenseBattle=null;if(success){p.owner='player';p.pop=Math.max(1,Math.floor(p.pop*.9));p.defense=10;p.fuel=rand(20,60);p.materials=rand(80,160);if(p.facilities)p.facilities.battery=0;result('占領成功',`${p.name}を占領しました。<br>${message}<br>残存艦：${f.ships.length}隻`,()=>{sel={kind:'planet',id:p.id};route=null;log(`${p.name}を占領しました。`,'good');render()})}else result('占領失敗',`${p.name}の占領に失敗しました。<br>${message}<br>残存艦：${f.ships.length}隻`,()=>{log(`${p.name}の占領に失敗しました。`,'bad');render()})}
function arrivalDialog(f,p){const buttons=[];if(canOccupy(f,p))buttons.push(['占領する',()=>{closeModal();occupyPlanet(f.id,p.id)}]);buttons.push(['OK',()=>{closeModal();sel={kind:'planet',id:p.id};route=null;render()}]);modal('星系到着',`<div class="routeOk"><b>${f.name}</b><br>${p.name}へ到着しました。${canOccupy(f,p)?'<br>戦艦と輸送船があるため占領を選択できます。':''}</div>`,buttons)}
function arrive(f){
 const p=S.planets[f.at];
 if(f.owner!=='player')return npcArrive(f,p);
 const enemy=S.fleets.find(x=>x.owner!=='player'&&x.at===p.id&&x.target===null&&x.ships.length);
 if(enemy)return startFleetBattle(f,enemy,p);
 if(f.ships.some(s=>s.type==='scout')){
  p.explored=true;
  if(!p.usable)return result('探査結果',`${p.name}<br>利用可能な惑星はありません。`,()=>render());
  if(!p.owner){p.owner='player';p.pop=10;return result('探査完了',`${p.name}を編入しました。`,()=>render())}
 }
 if(canRefuel(p))f.ships.forEach(s=>{const n=SHIPS[s.type].maxFuel-s.fuel,t=Math.min(n,p.fuel);s.fuel+=t;p.fuel-=t});
 arrivalDialog(f,p);
}
function npcArrive(f,p){
 const known=S.npcKnown[f.owner]||(S.npcKnown[f.owner]=[]);if(!known.includes(p.id))known.push(p.id);
 if(f.ships.some(s=>s.type==='scout')&&p.usable&&!p.owner){p.owner=f.owner;p.pop=rand(8,20);p.fuel=80;p.materials=80;f.order='新星系調査完了'}else f.order='哨戒';
 const playerFleet=S.fleets.find(x=>x.owner==='player'&&x.at===p.id&&x.target===null&&x.ships.length);if(playerFleet&&S.relations[f.owner]<0)startFleetBattle(playerFleet,f,p);else{f.target=null;f.progress=0;f.burn=0}
}
function canRefuel(p){return p.owner==='player'||(p.owner&&S.relations[p.owner]>=60)}function send(fid,pid,order){const f=S.fleets.find(x=>x.id===fid),r=routeInfo(f,pid);if(!r.ok)return log('航続距離外です。','warn');f.target=pid;f.progress=0;f.eta=r.turns;f.burn=Math.ceil(r.d*Math.max(.5,1-(commander(f)?.pilot||0)*.004))/r.turns;f.order=order;if(order==='探査')result('探査命令',`${f.name}<br>未踏星系-${pid}へ向かいます。`,()=>render())}
function annualRecruit(){const active=S.people.filter(p=>p.alive!==false);if(active.length>=20)return;for(let i=0;i<Math.min(rand(1,3),20-active.length);i++){const id=Math.max(...S.people.map(p=>p.id))+1;S.people.push({id,name:`候補生-${id}`,xp:0,pilot:rand(15,35),force:rand(15,35),diplomacy:rand(15,35),assignment:null,alive:true})}}
function facilityAllowed(p,k){if(p.type!=='gas')return true;return k==='fuelPlant'||FAC[k][1]==='orbital'}
function facilityCost(p,k){const lv=p.facilities[k]+1,m=2**(lv-1),d=FAC[k];return{lv,money:d[2]*m,materials:d[3]*m,turns:d[4]+(lv-1)*10}}
function facilityProblem(p,k){
 const c=facilityCost(p,k),problems=[];
 if(p.owner!=='player')problems.push('自国星系ではありません');
 if(!p.explored)problems.push('未探査星系です');
 if(!p.usable)problems.push('利用可能な惑星がありません');
 if(!facilityAllowed(p,k))problems.push('この惑星タイプでは建築できません');
 if(p.facilityQueue)problems.push(`現在、${FAC[p.facilityQueue.k][0]}を建築中です`);
 if(p.facilities[k]>=5)problems.push('最大レベルです');
 if(S.money<c.money)problems.push(`資金が${Math.ceil(c.money-S.money)}不足`);
 if(p.materials<c.materials)problems.push(`${p.name}の資材が${Math.ceil(c.materials-p.materials)}不足`);
 return problems;
}
function startFacility(pid,k){
 const p=S.planets[pid],c=facilityCost(p,k),problems=facilityProblem(p,k);
 if(problems.length)return result('建築できません',`<b>${FAC[k][0]} Lv${c.lv}</b><br>${problems.map(x=>`・${x}`).join('<br>')}<br><br>現在：資金${Math.floor(S.money)} / ${p.name}資材${Math.floor(p.materials)}<br>必要：資金${c.money} / 資材${c.materials}`,()=>openFacilities(pid));
 S.money-=c.money;p.materials-=c.materials;p.facilityQueue={k,remaining:c.turns,total:c.turns,lv:c.lv};
 result('建築開始',`${FAC[k][0]} Lv${c.lv}<br>資金${c.money}・資材${c.materials}を使用しました。<br>完成まで${c.turns}ターン`,()=>openFacilities(pid));
}
function processFacilities(){S.planets.filter(p=>p.facilityQueue).forEach(p=>{const q=p.facilityQueue;if(--q.remaining>0)return;p.facilities[q.k]=q.lv;if(q.k==='dock')p.dock=q.lv;if(q.k==='habitat')p.cap+=100;if(q.k==='defense')p.defense+=50;p.facilityQueue=null;log(`${p.name}で${FAC[q.k][0]}が完成しました。`,'good')})}
function openFacilities(pid=sel.kind==='planet'?sel.id:0){
 const p=S.planets[pid];if(!p||p.owner!=='player')return result('建築できません','自国星系を選択してください。',closeModal);
 const cards=Object.keys(FAC).map(k=>{const d=FAC[k],c=facilityCost(p,k),problems=facilityProblem(p,k),typeAllowed=facilityAllowed(p,k),hardDisabled=!typeAllowed||p.facilities[k]>=5||!!p.facilityQueue;return `<div class="facilityCard ${typeAllowed?'':'blocked'}"><div><b>${d[0]} Lv${p.facilities[k]}</b><small>${d[1]==='orbital'?'軌道施設':'地上施設'}</small>${problems.length?`<span class="shortage">${problems.join(' / ')}</span>`:'<span class="available">建築可能</span>'}</div><button data-fac="${k}" ${hardDisabled?'disabled':''}>${p.facilities[k]?'強化':'建築'}<small>資金${c.money}/資材${c.materials}/${c.turns}T</small></button></div>`}).join('');
 modal('施設建築',`<h3>${p.name} / ${TYPES[p.type][0]}</h3><div class="resourceSummary"><div>全体資金<br><b>${Math.floor(S.money)}</b></div><div>${p.name}の資材<br><b>${Math.floor(p.materials)}</b></div><div>建築枠<br><b>${p.facilityQueue?'使用中':'空き'}</b></div></div>${p.type==='gas'?'<div class="routeOk">燃料プラントと軌道施設を建築できます。</div>':''}${p.materials<120?`<div class="routeWarning">${p.name}の資材が不足しています。施設建築には、この星系へ資材を輸送する必要があります。</div>`:''}${p.facilityQueue?`<div class="buildQueue">建築中：${FAC[p.facilityQueue.k][0]} / 残り${p.facilityQueue.remaining}T</div>`:''}<div class="facilityGrid">${cards}</div>`,[['OK',closeModal]]);
 $('modalBody').querySelectorAll('[data-fac]').forEach(b=>b.onclick=()=>startFacility(pid,b.dataset.fac));
}
function processShips(){S.planets.filter(p=>p.buildQueue.length).forEach(p=>{const q=p.buildQueue[0];if(--q.remaining<=0&&p.dockPool.length<p.dock*4){p.dockPool.push(q.ship);p.buildQueue.shift();log(`${SHIPS[q.ship.type].name}が完成しました。`,'good')}})}function build(t){const p=S.planets.find(x=>x.owner==='player'&&x.dock),d=SHIPS[t];if(!p||S.money<d.cost[0]||p.materials<d.cost[1])return log('造船資源不足です。','warn');if(p.dockPool.length+p.buildQueue.length>=p.dock*4)return log('ドック上限です。','warn');S.money-=d.cost[0];p.materials-=d.cost[1];p.buildQueue.push({ship:{id:`s${Date.now()}`,type:t,hp:d.hp,fuel:d.maxFuel,level:1,upgrade:{}},remaining:d.turns,total:d.turns});result('建造開始',`${d.name}<br>完成まで${d.turns}ターン`,()=>render())}
function render(){stats();draw();fleetList();detail();$('diplomacy').innerHTML=''}function stats(){$('stats').innerHTML=`<span>${S.year}年 ${S.turn}/100</span><span>資金 ${Math.floor(S.money)}</span>`}function gauge(p){return `<div class="fuel"><i style="width:${p}%"></i></div>`}function fleetList(){$('fleets').innerHTML='';S.fleets.filter(f=>f.owner==='player').forEach(f=>{const b=document.createElement('button');b.className=`card ${sel.kind==='fleet'&&sel.id===f.id?'selected':''}`;b.innerHTML=`<b>${f.name}</b><br>${f.order}${gauge(Math.min(...f.ships.map(s=>s.fuel/SHIPS[s.type].maxFuel*100)))}`;b.onclick=()=>{sel={kind:'fleet',id:f.id};route={fid:f.id,pid:f.at};render()};$('fleets').appendChild(b)})}
function detail(){if(sel.kind==='fleet'){const f=S.fleets.find(x=>x.id===sel.id),r=route?routeInfo(f,route.pid):null;$('detail').innerHTML=`<h3>${f.name}</h3><div class="row"><span>司令官</span><b>${commander(f)?.name||'未任命'}</b></div><div class="row"><span>航続力</span><b>${range(f)}</b></div>`;$('actions').innerHTML=`<div class="command"><select id="cmd"><option>移動</option><option>探査</option></select><select id="dest">${S.planets.map(p=>`<option value="${p.id}" ${route?.pid===p.id?'selected':''}>${p.explored?p.name:`未踏星系-${p.id}`}</option>`).join('')}</select>${r?`<div class="${r.ok?'routeOk':'routeWarning'}">距離${r.d.toFixed(1)} / 航続力${range(f)}</div>`:''}<button id="issue" ${r?.ok?'':'disabled'}>命令を実行</button></div><button id="ok" class="primary">OK（基本画面へ）</button>`;$('dest').onchange=e=>{route={fid:f.id,pid:+e.target.value};detail();draw()};$('issue').onclick=()=>send(f.id,+$('dest').value,$('cmd').value);$('ok').onclick=()=>{sel={kind:'planet',id:f.at};route=null;render()};return}const p=S.planets[sel.id];$('detail').innerHTML=p.explored?`<h3>${p.name}</h3><div class="row"><span>種類</span><b>${TYPES[p.type][0]}</b></div><div class="row"><span>所属</span><b>${p.owner==='player'?'自国':p.owner||'無所属'}</b></div>`:`<h3>未踏星系-${p.id}</h3>`;const localOccupier=S.fleets.find(f=>f.owner==='player'&&canOccupy(f,p));$('actions').innerHTML=p.owner==='player'?'<button id="buildFac">この星系に施設を建築</button>':!p.explored?'<button id="scout">第1探査艦隊で探査</button>':localOccupier?'<button id="occupyHere">この星系を占領</button>':'';if($('buildFac'))$('buildFac').onclick=()=>openFacilities(p.id);if($('scout'))$('scout').onclick=()=>send(1,p.id,'探査');if($('occupyHere'))$('occupyHere').onclick=()=>occupyPlanet(localOccupier.id,p.id)}
function transform(){const w=map.clientWidth,h=map.clientHeight,scale=Math.min(w,h)/200;return{w,h,scale,ox:(w-200*scale)/2,oy:(h-200*scale)/2}}function screen(p,t=transform()){return{x:t.ox+p.x*t.scale,y:t.oy+p.y*t.scale}}function draw(){const t=transform(),d=devicePixelRatio||1;map.width=t.w*d;map.height=t.h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,t.w,t.h);S.planets.forEach(p=>{const q=screen(p,t);ctx.beginPath();ctx.arc(q.x,q.y,8,0,7);ctx.fillStyle=p.explored?TYPES[p.type][1]:'#718092';ctx.fill();ctx.fillStyle='#bfd0dc';ctx.fillText(p.explored?p.name:`未踏星系-${p.id}`,q.x+11,q.y+3)});if(sel.kind==='fleet'&&route){const f=S.fleets.find(x=>x.id===sel.id),q=screen(currentPos(f),t),r=range(f)*t.scale;ctx.strokeStyle='#5dd7ff';ctx.setLineDash([6,5]);ctx.beginPath();ctx.arc(q.x,q.y,r,0,7);ctx.stroke();ctx.setLineDash([]);const z=screen(S.planets[route.pid],t);ctx.strokeStyle=routeInfo(f,route.pid).ok?'#71df9c':'#ff7078';ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(z.x,z.y);ctx.stroke()}S.fleets.filter(f=>f.owner==='player'||S.planets[f.at]?.explored).forEach(f=>{const q=screen(currentPos(f),t);ctx.fillStyle=f.owner==='player'?'#fff':(FACS[f.owner]?.[1]||'#b7c0c8');ctx.beginPath();ctx.moveTo(q.x,q.y-8);ctx.lineTo(q.x+7,q.y+7);ctx.lineTo(q.x-7,q.y+7);ctx.fill()})}
function selectMap(e){const rect=map.getBoundingClientRect(),t=transform(),w={x:(e.clientX-rect.left-t.ox)/t.scale,y:(e.clientY-rect.top-t.oy)/t.scale};let best,bd=15;S.planets.forEach(p=>{const d=distance(p,w);if(d<bd){best=p;bd=d}});if(!best)return;if(sel.kind==='fleet'){route={fid:sel.id,pid:best.id};render()}else{sel={kind:'planet',id:best.id};render()}}
function openRoster(){modal('人事名簿',`<table class="roster">${S.people.filter(p=>p.alive).map(p=>{const r=rankByXp(p.xp);return `<tr><td><span class="rankBadge">${r[1]}</span></td><td>${r[0]} ${p.name}</td><td>操艦${p.pilot}</td><td>武力${p.force}</td><td>外交${p.diplomacy}</td></tr>`}).join('')}</table>`,[['OK',closeModal]])}function openSystems(){modal('星系一覧',`<div class="systems">${S.planets.map(p=>`<button class="sysrow" data-p="${p.id}"><span>${p.explored?p.name:`未踏星系-${p.id}`}</span><span>${p.owner||'不明'}</span><span>${Math.floor(p.pop)}</span><span>鉱${p.ore}/重${p.deut}</span><span>距離${distance(S.planets[0],p).toFixed(1)}</span><span>選択</span></button>`).join('')}</div>`,[['OK',closeModal]]);$('modalBody').querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{sel={kind:'planet',id:+b.dataset.p};closeModal();render()})}function openDock(){const p=S.planets.find(x=>x.owner==='player'&&x.dock);modal('造船ドック',`<h3>${p.name} Lv${p.dock}</h3>${p.buildQueue.map(q=>`<div class="buildQueue">${SHIPS[q.ship.type].name} 残${q.remaining}T</div>`).join('')}${p.dockPool.map(s=>`<div class="shipCard">${SHIPS[s.type].name}</div>`).join('')}`,[['OK',closeModal]])}function openShips(){const a=[];S.fleets.forEach(f=>f.ships.forEach(s=>a.push([s,f.name])));S.planets.forEach(p=>p.dockPool.forEach(s=>a.push([s,p.name+'ドック'])));modal('宇宙船ステータス',`<div class="shipGrid">${a.map(([s,p])=>`<div class="shipCard"><b>${SHIPS[s.type].name}</b><br>${p}<br>耐久${s.hp}/${SHIPS[s.type].hp}<br>攻撃${SHIPS[s.type].atk}<br>防御${SHIPS[s.type].def}<br>燃料${Math.floor(s.fuel)}/${SHIPS[s.type].maxFuel}</div>`).join('')}</div>`,[['OK',closeModal]])}
function log(text,k='info'){history.unshift({text,k});$('notice').innerHTML=`<span class="${k}">${text}</span>`}function modal(t,b,buttons){speed(0);$('modalTitle').textContent=t;$('modalBody').innerHTML=b;$('modalButtons').innerHTML='';buttons.forEach(([x,f])=>{const b=document.createElement('button');b.textContent=x;b.onclick=f;$('modalButtons').appendChild(b)});$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}function result(t,b,f){modal(t,`<div class="routeOk">${b}</div>`,[['OK',()=>{closeModal();if(f)f()}]])}function speed(v){clearInterval(timer);if(v)timer=setInterval(tick,3000/v)}function save(m){localStorage.setItem('pg150',JSON.stringify(S));if(m)log('保存しました。','good')}function load(){const d=localStorage.getItem('pg150');if(d){S=JSON.parse(d);closeModal();render()}}
map.onpointerup=selectMap;window.onresize=draw;document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>speed(+b.dataset.speed));document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build));$('facilityMenu').onclick=()=>openFacilities();$('roster').onclick=openRoster;$('systemMenu').onclick=openSystems;$('dockMenu').onclick=openDock;$('shipStatusMenu').onclick=openShips;$('saveMenu').onclick=()=>modal('セーブ管理','',[['保存',()=>save(true)],['読込',load],['OK',closeModal]]);$('history').onclick=()=>modal('通知履歴',history.map(x=>`<div class="card ${x.k}">${x.text}</div>`).join(''),[['OK',closeModal]]);$('newWorld').onclick=()=>result('新しい星域','新しい星域を作成します。',newGame);newGame();
